development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: cgame_development
  pool:     5
  username: cgame
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: cgame_test
  pool:     5
  username: cgame
  password:
  template: template0
